name: main

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push to Apps Script
        uses: daikikatsuragawa/clasp-action@v1
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'push'
          

